- title: "An application of Reinforced Urn Process to advice network data"
  authors:
    - name: "Stefano Peluso"
      remedi-lab: false
    - name: "Antonietta Mira"
      remedi-lab: true
    - name: "P Muliere"
      remedi-lab: false
    - name: "Francesca Pallotti"
      remedi-lab: false
    - name: "Alessandro Lomi"
      remedi-lab: false
  year: 2016
  journal: ""
  link: "https://boa.unimib.it/handle/10281/266147"
